#!/usr/bin/env python3
"""Generate and validate project-scoped Codex agents.

`agents/` (symlinked as `.claude/agents/`) remains the source of truth for role prompts. Codex-specific
metadata and sandbox settings live in PROFILE_CONFIG below so generation is
deterministic and a new checkout does not depend on pre-existing output files.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / ".claude" / "agents"
TARGET = Path(__file__).resolve().parent / "agents"

HEADER = "# Ported from .claude/agents/{name}.md. Edit the source, then regenerate.\n"
REGEN = "# Generated by .codex/sync-agents.py -- do not edit this file directly.\n"

# Claude's source descriptions include routing examples. Codex discovery
# metadata should remain concise and human-facing.
PROFILE_CONFIG = {
    "code-reviewer": ("Reviews M/L application governing documents and application-code changes; never authors or merges.", "gpt-5.6-sol", "high", "read-only"),
    "devops-infra-expert": ("Owns IaC, Kubernetes manifests, delivery infrastructure, and operational reliability.", "gpt-5.6-sol", "high", "workspace-write"),
    "lead-system-architect": ("Makes architecture decisions and authors governing technical plans; never implements.", "gpt-5.6-sol", "high", "workspace-write"),
    "product-owner": ("Defines requirements, acceptance criteria, scope, and priorities; never implements.", "gpt-5.6-sol", "high", "workspace-write"),
    "senior-software-engineer": ("Implements approved application-code changes and tests; authors and merges but never reviews.", "gpt-5.6-sol", "medium", "workspace-write"),
    "seo-specialist": ("Runs documentation-only organic-search and AI-visibility audits.", "gpt-5.6-sol", "medium", "workspace-write"),
    "team-lead-coordinator": ("Coordinates the delivery team and its dependencies; never performs specialist work.", "gpt-5.6-sol", "high", "workspace-write"),
}

VOCAB = """## Codex runtime notes

This prompt is generated from `.claude/agents/{stem}.md`, which is written for Claude Code.
Everything after these notes is that prompt verbatim. Where it says:

- "the Agent tool", "the Task tool", "spawn"  -- use `spawn_agent` with the named agent type.
- "subagent_type"  -- use the custom agent's `name`; project agents are discovered from `.codex/agents/`.
- "SendMessage" or "the mailbox"  -- use `send_message`; `followup_task` redirects an idle delegate.
- "the shared task list", "TodoWrite", "TaskCreate"  -- Codex has no shared task list. Keep the
  dependency plan in your own response and in the target project's SDD artifacts, and release a
  handoff with `send_message` only after checking its prerequisite result.
- "teammate"  -- a delegate spawned with `spawn_agent`.
- "Claude Code Agent Teams", `TeamCreate`  -- not available. Use Codex's collaboration tools;
  there is no team object to create or clean up.
- "list_agents" / "wait_agent" are how you read delegate state and await updates.

### GitLab access

Before any GitLab API or authenticated Git transport operation, load and follow
`$gitlab-access` from `.agents/skills/gitlab-access/SKILL.md`.

<!-- END CODEX RUNTIME NOTES -->

"""

COORDINATOR_MODE = """## Operating Mode: Codex multi-agent coordination

**You are the coordinator for Codex's multi-agent system.** Project custom agents are discovered
from `.codex/agents/`, and multi-agent support is enabled by default. Treat the Codex
collaboration-tool contract as authoritative.

- Each delegate is an independent Codex agent with its own context and configuration.
- Use `spawn_agent` with the registered role name for a bounded, task-specific delegation.
- Use `send_message` for direct coordination, `followup_task` to continue or redirect an idle delegate,
  `list_agents` to inspect live state, and `wait_agent` to await updates.
- Codex has no shared task-list tool. Keep the dependency plan in your coordination response and in
  the target project's required SDD artifacts; hand off only after checking prerequisite results.

### Preconditions and halt-on-degradation rule (NEVER violate)

At run start, verify that `spawn_agent`, `send_message`, `followup_task`, `list_agents`, and
`wait_agent` are available. If delegation is unavailable, halt: do not write code, ADRs,
requirements, or infrastructure artifacts on a specialist's behalf; state which capability is
unavailable and ask the caller to run where Codex collaboration tools are enabled.

Silent role collapse is a failure. Do not produce partial specialist work that could be mistaken
for successful coordination.

### Mapping roles to registered Codex agent types

| Role | Registered agent type |
| :-- | :-- |
| DevOps Engineer | `devops-infra-expert` |
| Lead System Architect | `lead-system-architect` |
| Senior Software Engineer | `senior-software-engineer` |
| Code Reviewer | `code-reviewer` |
| Product Owner | `product-owner` |

### Canonical workflow (follow on every team task)

1. **Decide whether delegation is warranted.** Use focused, bounded delegates for multi-discipline,
   parallel, or high-risk work; retain coordination only for process/status work.
2. **Plan dependencies before spawning.** Record assignee, deliverable, prerequisite, acceptance
   criteria, and handoff in the response and target project's SDD artifacts where required.
3. **Spawn delegates** with task-specific prompts containing target context, inputs, deliverables,
   dependencies, consultation requirements, and plan-approval criteria.
4. **Require plan approval for risky work.** Production-touching work, schema changes,
   infrastructure mutations, and large refactors need tests and rollback in the approved plan.
5. **Coordinate explicitly.** Provide prerequisite outputs before handoff. Implementation proceeds
   only after architect and product-owner consultations are complete and cross-checked.
6. **Monitor and wait.** Check delegate state and artifacts before acting on a completion or blocker.
7. **Finish only after every required delegate reports and the evidence is checked.**
"""


def source_body(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n.*?\n---\n", text, re.DOTALL)
    if not match:
        raise ValueError(f"{path}: no YAML frontmatter found")
    return text[match.end() :].strip("\n")


def split_heading(text: str, heading: str, path: Path) -> tuple[str, str]:
    marker = "\n" + heading
    index = text.find(marker)
    if index == -1:
        raise ValueError(f"{path}: heading {heading!r} not found")
    return text[:index].rstrip("\n"), text[index + 1 :].rstrip("\n")


def adapted_body(path: Path) -> str:
    body = source_body(path)
    if path.stem != "team-lead-coordinator":
        return body
    intro, rest = split_heading(body, "## Operating Mode: Claude Code Agent Team", path)
    _, synced = split_heading(rest, "## Your Team", path)
    return f"{intro}\n\n{COORDINATOR_MODE}\n\n{synced}"


def render(path: Path) -> str:
    stem = path.stem
    description, model, effort, sandbox = PROFILE_CONFIG[stem]
    body = adapted_body(path)
    if "'''" in body:
        raise ValueError(f"{path}: body contains triple single quotes")
    output = "\n".join([
        HEADER.format(name=stem).rstrip(),
        REGEN.rstrip(),
        f"name = {json.dumps(stem)}",
        f"description = {json.dumps(description)}",
        f"model = {json.dumps(model)}",
        f"model_reasoning_effort = {json.dumps(effort)}",
        f"sandbox_mode = {json.dumps(sandbox)}",
        "",
        f"developer_instructions = '''{VOCAB.format(stem=stem)}{body}\n'''",
        "",
    ])
    parsed = tomllib.loads(output)
    for required in ("name", "description", "developer_instructions"):
        if not isinstance(parsed.get(required), str) or not parsed[required].strip():
            raise ValueError(f"{path}: generated profile lacks required {required!r}")
    return output


def expected_outputs() -> dict[Path, str]:
    sources = {path.stem: path for path in SOURCE.glob("*.md")}
    if set(sources) != set(PROFILE_CONFIG):
        raise ValueError(
            "source/profile mismatch: "
            f"missing config={sorted(set(sources) - set(PROFILE_CONFIG)) or 'none'}, "
            f"missing source={sorted(set(PROFILE_CONFIG) - set(sources)) or 'none'}"
        )
    return {TARGET / f"{stem}.toml": render(path) for stem, path in sorted(sources.items())}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated profiles are stale")
    args = parser.parse_args()
    try:
        expected = expected_outputs()
    except (OSError, ValueError, tomllib.TOMLDecodeError) as error:
        print(error, file=sys.stderr)
        return 1

    actual = set(TARGET.glob("*.toml")) if TARGET.is_dir() else set()
    unexpected = actual - set(expected)
    drifted = [path for path, content in expected.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]

    if args.check:
        for path in sorted(drifted):
            print(f"stale: {path.relative_to(ROOT)}")
        for path in sorted(unexpected):
            print(f"unexpected: {path.relative_to(ROOT)}")
        if drifted or unexpected:
            return 1
        print(f"{len(expected)} Codex agent profile(s) valid and in sync")
        return 0

    TARGET.mkdir(parents=True, exist_ok=True)
    for path in sorted(unexpected):
        path.unlink()
        print(f"removed {path.relative_to(ROOT)}")
    for path, content in expected.items():
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            print(f"{path.relative_to(ROOT)} -- unchanged")
            continue
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
